server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
#    name: tcs-poc-api-gateway
    name: api-gateway
#    config:
#     import: optional:configserver:http://localhost:9004
  cloud:
    gateway:
      routes:
        
      - id: bootClient1
#        uri: http://localhost:8050/bootClient1/
        uri: lb://boot-client1/
        predicates:
        - Path=/bootClient1/**
        
      - id: bootClient2
        uri: lb://boot-client2/
        predicates:
        - Path=/bootClient2/**
        
      - id: camelFile
        uri: lb://camel-file/
        predicates:
        - Path=/camel-file/**
         
      - id: config-server
        uri: lb://config-server/
        predicates:
        - Path=/config-server/**

    boot:
    admin:
    client:
     url: http://localhost:8761/admin
          
     
   
    
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#    logfile:
#    external-file: logs/logfile.log
#        
#logging:
#  file:
#    name: logs/logfile.log
